name: Release

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build-release:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node JS
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: yarn
      - run: yarn install --ignore-engines
      - run: yarn lint:nofix
      - run: yarn test
      - name: Release to npm 🚀
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
